version: "3.1"
services:
  postgres:
    image: postgres
    hostname: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 6443c7aaac2b404d83d854d146e
      POSTGRES_DB: dispatch
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: janitor@contractshark.io
      PGADMIN_DEFAULT_PASSWORD: curious-canoe-juice-hood
    restart: unless-stopped

volumes:
  postgres-data:
